/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pnlResults.java
 *
 * Created on Apr 20, 2010, 2:24:14 PM
 */

package cytoscape.MyRBN;

import cytoscape.CyEdge;
import cytoscape.CyNetwork;
import cytoscape.CyNode;
import cytoscape.Cytoscape;
import cytoscape.data.CyAttributes;
import cytoscape.layout.CyLayoutAlgorithm;
import cytoscape.layout.CyLayouts;
import cytoscape.task.ui.JTaskConfig;
import cytoscape.task.util.TaskManager;
import cytoscape.view.CyNetworkView;
import giny.model.Edge;
import giny.model.Node;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Vector;
import javax.swing.AbstractListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import myrbn.MyRBN;

/**
 *
 * @author Le Duc Hau
 */
public class pnlFFL extends javax.swing.JPanel {

    /** Creates new form pnlResults */
    public pnlFFL() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grbFBL = new javax.swing.ButtonGroup();
        grbPath = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        btnShowFBLPath = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1062, 235));
        setMinimumSize(new java.awt.Dimension(1062, 235));
        setPreferredSize(new java.awt.Dimension(1044, 254));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Results", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Node 1", "Node 2", "Node 3", "Node 4"
            }
        ));
        tblResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResultMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblResultMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblResult);

        btnShowFBLPath.setText("Show");
        btnShowFBLPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowFBLPathActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 10));
        jLabel3.setText("Choose all consecutive paths beloning to one Feed-forward Loop  to view");

        lblInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(255, 0, 0));
        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInfo.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnShowFBLPath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                        .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnShowFBLPath)
                    .addComponent(lblInfo)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblResultMouseClicked

    
    private void btnShowFBLPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowFBLPathActionPerformed
        // TODO add your handling code here:
        try{
            int ri[] = this.tblResult.getSelectedRows();
            
            if(ri.length<=0){
                return;
            }
            
            CyNetwork subNetwork=Cytoscape.createNetwork("MOTIF_",true);
            int i,j;
            List<Node> listNode=Main.workingNetwork.nodesList();
            Iterator<Node> it = listNode.iterator();
            CyNode aNode;
            CyEdge aEdge;

            
            //JOptionPane.showMessageDialog(Cytoscape.getDesktop(), ri.length + ":" + this.tblResult.getSelectedRows().length);
            for(int r=0;r<ri.length;r++){
                //JOptionPane.showMessageDialog(Cytoscape.getDesktop(),"Column Count: " + tblResult.getColumnCount() + ", r=" + r);
                int TotalNode;
                TotalNode=0;
                for(i=3;i<tblResult.getColumnCount();i++)
                    if(this.tblResult.getValueAt(ri[r], i)!=null) TotalNode++;

                //JOptionPane.showMessageDialog(Cytoscape.getDesktop(),"TotalNode=" + TotalNode);
                subNetwork.setTitle(subNetwork.getTitle()+"(");
                for(i=1;i<TotalNode+1;i++){
                    if(this.tblResult.getValueAt(ri[r], i+2)!=null){
                        //JOptionPane.showMessageDialog(Cytoscape.getDesktop(),"Node: Row Id: " + ri[r] + ", Col Id: " + i + ", Value: " + this.tblResult.getValueAt(ri[r], i));

                        aNode=Cytoscape.getCyNode(this.tblResult.getValueAt(ri[r], i+2).toString(), true);
                        subNetwork.addNode(aNode);
                        subNetwork.setTitle(subNetwork.getTitle()+aNode.getIdentifier()+"_");

                        //Visualize Input and Output nodes
                        CyAttributes cyNodeAtt = Cytoscape.getNodeAttributes();
                        if(i==1 || i==TotalNode){
                            Main.workingNetwork.setSelectedNodeState(aNode, true);
                            if(i==1){
                                cyNodeAtt.setAttribute(aNode.getIdentifier(), "InOut", "Input");
                            }else{
                                cyNodeAtt.setAttribute(aNode.getIdentifier(), "InOut", "Output");
                            }
                        }else{
                            cyNodeAtt.setAttribute(aNode.getIdentifier(), "InOut", "Intermediate");
                        }
                    }
                }
                subNetwork.setTitle(subNetwork.getTitle().substring(0, subNetwork.getTitle().length()-1));
                subNetwork.setTitle(subNetwork.getTitle()+")_");
                for(i=1;i<TotalNode;i++){
                    if(this.tblResult.getValueAt(ri[r], i+2)!=null){
                        //JOptionPane.showMessageDialog(Cytoscape.getDesktop(),"Edge: Row Id: " + ri[r] + ", Col Id: " + i + ", Value: " + this.tblResult.getValueAt(ri[r], i));
                        //JOptionPane.showMessageDialog(Cytoscape.getDesktop(),"NumOfIna: " + MyRBN.rndina.size());
                        for(j=0;j<MyRBN.rndina.size();j++){
                            //JOptionPane.showMessageDialog(Cytoscape.getDesktop(),MyRBN.rndina.get(j).NodeSrc.NodeID+","+Integer.parseInt(this.tblResult.getValueAt(ri[r], i).toString()) +","+ MyRBN.rndina.get(j).NodeDst.NodeID+","+Integer.parseInt(this.tblResult.getValueAt(ri[r], i+1).toString()));
                            if(MyRBN.rndina.get(j).NodeSrc.compareTo(this.tblResult.getValueAt(ri[r], i+2).toString())==0 && MyRBN.rndina.get(j).NodeDst.compareTo(this.tblResult.getValueAt(ri[r], i+2+1).toString())==0){
                                aEdge=Cytoscape.getCyEdge(MyRBN.rndina.get(j).NodeSrc,Integer.toString(j),MyRBN.rndina.get(j).NodeDst,Integer.toString(MyRBN.rndina.get(j).InteractionType));
                                subNetwork.addEdge(aEdge);
                                break;
                            }
                        }

                    }

                }
                //JOptionPane.showMessageDialog(Cytoscape.getDesktop(),"End of row: " + r);
            }
            subNetwork.setTitle(subNetwork.getTitle().substring(0, subNetwork.getTitle().length()-1));
            //Add network properties
            CyAttributes cyNetworkAttrs=  Cytoscape.getNetworkAttributes();
            cyNetworkAttrs.setAttribute(subNetwork.getIdentifier(), "NetworkType", "MOTIF");
            // Inform others via property change event.
            Cytoscape.firePropertyChange(Cytoscape.ATTRIBUTES_CHANGED, null, null);

            CyLayoutAlgorithm algo = CyLayouts.getLayout("force-directed");
            CyNetworkView curNetworkView = Cytoscape.getNetworkView(subNetwork.getIdentifier());
            curNetworkView.applyLayout(algo);
        }catch(Exception e){
            JOptionPane.showMessageDialog(Cytoscape.getDesktop(), e.getMessage());
        }
    }//GEN-LAST:event_btnShowFBLPathActionPerformed

    private void tblResultMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultMouseReleased
        // TODO add your handling code here:
          try{
            
            int i,j;
            List<Node> listNode=Main.workingNetwork.nodesList();
            Iterator<Node> it = listNode.iterator();

            //Highlight in RBN
            List<Edge> listEdge = Main.workingNetwork.edgesList();
            Iterator<Edge> ite = listEdge.iterator();

            Main.workingNetwork.setSelectedEdgeState(listEdge,false);
            Main.workingNetwork.setSelectedNodeState(listNode,false);

            CyNetworkView curNetworkView = Cytoscape.getNetworkView(Main.workingNetwork.getIdentifier());

            curNetworkView.redrawGraph(true, true);

            int[] ri = this.tblResult.getSelectedRows();
            int k;

            while(it.hasNext()){
                Node anode=(Node)it.next();
                for(k=0;k<ri.length;k++){
                    for(i=1;i<tblResult.getColumnCount();i++){
                        if(this.tblResult.getValueAt(ri[k], i)!=null){
                            if(anode.getIdentifier().compareTo(this.tblResult.getValueAt(ri[k], i).toString())==0){
                                Main.workingNetwork.setSelectedNodeState(anode, true);
                                //JOptionPane.showMessageDialog(Cytoscape.getDesktop(), anode.getIdentifier());
                                break;
                            }
                        }
                    }
                }
            }


            while(ite.hasNext()){
                Edge aedge=(Edge)ite.next();
                for(k=0;k<ri.length;k++){
                    for(i=1;i<tblResult.getColumnCount();i++){
                        if(this.tblResult.getValueAt(ri[k], i)!=null){
                            if(aedge.getSource().getIdentifier().compareTo(this.tblResult.getValueAt(ri[k], i-1).toString())==0 && aedge.getTarget().getIdentifier().compareTo(this.tblResult.getValueAt(ri[k], i).toString())==0){
                                Main.workingNetwork.setSelectedEdgeState(aedge, true);
                                break;
                            }
                        }

                    }
                }
            }

            //CyNetworkView curNetworkView = Cytoscape.getCurrentNetworkView();
            curNetworkView.redrawGraph(true, true);


        }catch(Exception e){
            JOptionPane.showMessageDialog(Cytoscape.getDesktop(), "Error: " + e.toString());
        }
    }//GEN-LAST:event_tblResultMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowFBLPath;
    private javax.swing.ButtonGroup grbFBL;
    private javax.swing.ButtonGroup grbPath;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JLabel lblInfo;
    public static javax.swing.JTable tblResult;
    // End of variables declaration//GEN-END:variables

}

